#include <stdio.h>
#include <castle/castle.h>

#define print(_f, _a...)                                                            \
do {                                                                                \
    int ret = fprintf(fp, _f, ##_a);                                                \
    if (ret < 0)                                                                    \
        goto err_out;                                                               \
} while(0)

int main(int argc, char *argv[])
{
    FILE *fp;

    printf("Started\n");

    /* Takes the file name that the generated java code should be copied to. */
    if (argc != 2)
    {
        fprintf(stderr, "Usage: ./a.out <output.java>\n");
        return -1;
    }

    fp = fopen(argv[1], "w");
    if (fp == NULL)
    {
        fprintf(stderr, "Failed open file %s\n", argv[1]);
        return -1;
    }

    /* Desclaimer. */
    print(
"/**\n"
" * Don't try to change this file directly. This file is auto-generated by\n"
" * enum_class_gen.c. To add a new error code, change castle_public.h.\n"
" * If this java file is buggy then either fix it in enum_class_gen.c\n"
" * or talk to BM.\n"
" */\n\n");

    /* Attach this to package castle. */
    print("package com.acunu.castle;\n\n");

    /* enum class. */
    print("public enum CastleError {\n\n");

    /* Define enum types for all error codes defined in fs.hg/kernel/castle_public.h. */
#undef CASTLE_ERROR_CODE
#define CASTLE_ERROR_CODE(err_no, err_code, err_str)                                \
    print("   %s (%d, \"%s\"),\n", #err_code, err_no, err_str);
    CASTLE_ERRORS

    /* Continue enum class definitiion. */
    print(
"   ERR_XCARE(111, \"ERR_XCARE\");\n\n"
"   public int errno;\n"
"   public String str;\n\n"
"   CastleError(int errno, String str)\n"
"   {\n"
"       this.errno = errno;\n"
"       this.str   = str;\n"
"   }\n"
"}\n");

    fclose(fp);

    return 0;

err_out:
    fprintf(stderr, "Failed to write to output file: %s\n", argv[1]);
    fclose(fp);

    return -1;
}
